class LiquidsoapConfigService
  CONFIG_PATH = Rails.root.join("storage", "liquidsoap", "radio.liq")

  def self.call
    new.call
  end

  def call
    stations = RadioStation.where.not(status: "stopped").includes(:playlist)
    config = generate(stations)
    write(config)
    config
  end

  private

  def generate(stations)
    <<~LIQ
      # Generated by synthwaves.fm — do not edit manually
      # Generated at: #{Time.current.iso8601}

      settings.log.level.set(3)

      #{settings_block}

      #{stations.map { |s| station_block(s) }.join("\n\n")}
    LIQ
  end

  def settings_block
    <<~LIQ
      rails_host = environment.get("RAILS_HOST", "localhost:3000")
      rails_protocol = environment.get("RAILS_PROTOCOL", "http")
      auth_token = environment.get("LIQUIDSOAP_API_TOKEN", "")
      icecast_host = environment.get("ICECAST_HOST", "localhost")
      icecast_port = int_of_string(environment.get("ICECAST_PORT", "8000"))
      icecast_password = environment.get("ICECAST_SOURCE_PASSWORD", "hackme")
    LIQ
  end

  def station_block(station)
    id = station.id
    slug = station.mount_point.delete_prefix("/").delete_suffix(".mp3")
    safe_id = slug.tr("-", "_")

    <<~LIQ
      # Station #{id}: #{station.playlist.name}
      def next_track_#{safe_id}() =
        result = http.get(
          headers=[("Authorization", "Bearer " ^ auth_token)],
          rails_protocol ^ "://" ^ rails_host ^ "/api/internal/radio_stations/#{id}/next_track"
        )
        if result.status_code == 200 then
          let json.parse ({url = ""} : {url: string}) = result
          url
        else
          ""
        end
      end

      station_#{safe_id} = request.dynamic(id="#{slug}", fun () -> next_track_#{safe_id}())
      #{crossfade_line(station, safe_id)}

      station_#{safe_id} = mksafe(station_#{safe_id})

      output.icecast(
        %mp3(bitrate=#{station.bitrate}),
        host=icecast_host,
        port=icecast_port,
        password=icecast_password,
        mount="#{station.mount_point}",
        name=#{liquidsoap_string(station.playlist.name)},
        station_#{safe_id}
      )
    LIQ
  end

  def crossfade_line(station, safe_id)
    if station.crossfade
      "station_#{safe_id} = crossfade(duration=#{station.crossfade_duration}, station_#{safe_id})"
    else
      ""
    end
  end

  def liquidsoap_string(str)
    "\"#{str.gsub("\\", "\\\\\\\\").gsub('"', '\\"')}\""
  end

  def write(config)
    dir = CONFIG_PATH.dirname
    FileUtils.mkdir_p(dir)
    File.write(CONFIG_PATH, config)
  end
end
